export const MOCKUP_EVENTS = [
  {
    id: 1,
    type: 'Programa y Proyectos',
    name: 'Escalando',
    organization: 'CEVAMAR',
    overseers: ['Andrea Rojas'],
    goal: 'Programa gratuito de educación en salud mental y bienestar para los adolescentes, con el objetivo de combatir la falta de alfabetización de salud mental, así como sensibilizar a la institución educativa para que tenga en cuenta la temática y contribuir al bienestar psicológico de la juventud en la Isla de Margarita.',
    participants: ['Fred', 'Moises', 'Flavio'],
    startDate: '10/02/2022',
    endDate: '10/08/2022',
    observations: 'Culminado sin problemas.',
    status: 'Completado',
  },
  {
    id: 2,
    type: 'Programa y Proyectos',
    name: 'Wisibilizala 6ta Edicion',
    organization: 'Wisibilizala',
    overseers: ['Luzmary Rojas'],
    goal: 'Romper estereotipos de género asociados a ciencia, tecnología, ingeniería y matemáticas (STEM). Promover la alfabetización tecnológica, la creatividad y el trabajo en grupo desde edades tempranas. Dar visibilidad al importante papel de la mujer actual en ciencia, tecnología, ingeniería y matemáticas',
    participants: ['Fred', 'Moises'],
    startDate: '09/28/2022',
    endDate: '10/05/2022',
    observations: 'Culminado sin problemas.',
    status: 'Incompleto',
  },
  {
    id: 3,
    type: 'Reto de Ciencias Naturales',
    name: 'Cocinando Ciencia: Plastilina Casera',
    organization: 'MPPE',
    overseers: ['Jose Velazques', 'Yraida Marcano'],
    goal: 'Elaborar con materiales de uso cotidiano una pastilina casera con la cual se puede propiciar el desarrolo de la motricidad y laceatividad en los niños.',
    participants: ['Fred', 'Moises', 'Flavio', 'Alberto'],
    startDate: '09/02/2022',
    endDate: '09/10/2022',
    observations: 'Corte de luz perjudico el evento.',
    status: 'Cancelado',
  },
];
