export const MOCKUP_EVENTS = [
  {
    id: 1,
    type: 'Programa y Proyectos',
    name: 'Escalando',
    organization: 'CEVAMAR',
    overseers: [{ fullname: 'Andrea Rojas' }],
    goal: 'Programa gratuito de educación en salud mental y bienestar para los adolescentes, con el objetivo de combatir la falta de alfabetización de salud mental, así como sensibilizar a la institución educativa para que tenga en cuenta la temática y contribuir al bienestar psicológico de la juventud en la Isla de Margarita.',
    participants: [
      { fullname: 'Fred' },
      { fullname: 'Moises' },
      { fullname: 'Flavio' },
    ],
    startDate: '2022-02-10',
    endDate: '2022-08-10',
    observations: 'Culminado sin problemas.',
    status: 'Completado',
  },
  {
    id: 2,
    type: 'Programa y Proyectos',
    name: 'Wisibilizala 6ta Edicion',
    organization: 'Wisibilizala',
    overseers: [{ fullname: 'Luzmary Rojas' }],
    goal: 'Romper estereotipos de género asociados a ciencia, tecnología, ingeniería y matemáticas (STEM). Promover la alfabetización tecnológica, la creatividad y el trabajo en grupo desde edades tempranas. Dar visibilidad al importante papel de la mujer actual en ciencia, tecnología, ingeniería y matemáticas',
    participants: [{ fullname: 'Fred' }, { fullname: 'Moises' }],
    startDate: '2022-09-28',
    endDate: '2022-05-10',
    observations: 'Culminado sin problemas.',
    status: 'En Progreso',
  },
  {
    id: 3,
    type: 'Reto de Ciencias Naturales',
    name: 'Cocinando Ciencia: Plastilina Casera',
    organization: 'MPPE',
    overseers: [{ fullname: 'Jose Velazques' }, { fullname: 'Yraida Marcano' }],
    goal: 'Elaborar con materiales de uso cotidiano una pastilina casera con la cual se puede propiciar el desarrolo de la motricidad y laceatividad en los niños.',
    participants: [
      { fullname: 'Fred' },
      { fullname: 'Moises' },
      { fullname: 'Flavio' },
      { fullname: 'Alberto' },
    ],
    startDate: '2022-02-09',
    endDate: '2022-10-09',
    observations: 'Corte de luz perjudico el evento.',
    status: 'Cancelado',
  },
];
