export const MOCKUP_EVENTS = [
  {
    "project": "FINANZAS EN MI ESCUELA (FEME)",
    "organization": "Val-u",
    "mission": "Fometar la educación financiera en jóvenes entre 10 y 19 años, desarrollado en lecciones semanales en módulos trimestrales de forma online.",
    "attendees": "Estudiantes de 5to. grado de Educación Primaria a 5to. año de Media General",
    "manager": "Coordinadoras: Liliana Montoya (5to. y 6to. grado), Angélica Pérez (1er. y 2do. año), Rossana Carrillo (3ero., 4to. y 5to. año)",
    "date": "08/05/2022",
    "observations": "Se incorporó al grupo de 4to. grado - Finalista: Mujeres en acción (grupo de 8 estudiantes)",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 25,
    "status": "completed"
  },
  {
    "project": "ESCALANDO",
    "organization": "CEVAMAR",
    "mission": "Programa gratuito de educación en salud mental y bienestar para los adolescentes, con el objetivo de combatir la falta de alfabetización de salud mental, así como sensibilizar a la institución educativa para que tenga en cuenta la temática y contribuir al bienestar psicológico de la juventud en la Isla de Margarita.",
    "attendees": "Estudiantes de 3er. año (A y B) de Media General",
    "manager": "Andrea Rojas (orientadora). Andrea Tedaldi",
    "date": "25/12/2021",
    "observations": "Culminado",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 18,
    "status": "completed"
  },
  {
    "project": "WISIBILÍZALA 6ta. Edición",
    "organization": "WISIBILÍZALA",
    "mission": "Romper estereotipos de género asociados a ciencia, tecnología, ingeniería y matemáticas (STEM). Promover la alfabetización tecnológica, la creatividad y el trabajo en grupo desde edades tempranas. Dar visibilidad al importante papel de la mujer actual en ciencia, tecnología, ingeniería y matemáticas",
    "attendees": "Estudiantes de 3er. grado (A y B) y 4to. grado de Primaria",
    "manager": "Docentes: Luzmary Rojas, Juan Carlos Marín - Docentes de aula",
    "date": "12/07/2022",
    "observations": "Entregado el 16 de mayo. Finalistas: Mujeres en acción (8 estudiantes de 4to. grado)",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 14,
    "status": "pending"
  },
  {
    "project": "Cubagua, Historia y Leyenda",
    "organization": "D´buceo y Kayak con propósito",
    "mission": "Acercamiento a la isla de Cubagua a través de la visualización de un documental (todo esto relacionado al proyecto desarrollado en el Nivel de Media General)",
    "attendees": "Estudiantes de Media General (de 1ero. a 5to. año)",
    "manager": "Docente Rossana Carrillo. José Montes (D´buceo), Giancarlo Orco (kayak con propósito)",
    "date": "05/10/2021",
    "observations": "Culminado: participación de todos los estudiantes de MG. Cierre de la actividad en el P.A. \"Conociendo Nueva Esparta a través de El Ángel\"",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 15,
    "status": "pending"
  },
  {
    "project": "Reporteros Zona Escolar",
    "organization": "LA MEGA",
    "mission": "Promover el periodismo escolar a través de la campaña #ZEreportero, donde los chicos en edades principalmente de bachillerato elaboran un video corto (de máximo 30-40 segundos) donde cuentan alguna actividad que se estén realizando en el colegio.",
    "attendees": "Estudiantes del Nivel de Educación Media General",
    "manager": "Docente: Lilyeth Marval, Margaret Rojas",
    "date": "21/09/2021",
    "observations": "Envío de 6 videos",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 17,
    "status": "completed"
  },
  {
    "project": "V Encuentro de niños, niñas y jóvenes lectores. Capítulo Nueva Esparta.",
    "organization": "ANDIEP",
    "mission": "Fortalecer la lectura y escritura a través de la creación e interpretación de textos narrativos.",
    "attendees": "Estudiantes de Primaria y MG",
    "manager": "Ana María Núñez",
    "date": "04/11/2021",
    "observations": "Culminado",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 22,
    "status": "canceled"
  },
  {
    "project": "I encuentro de Galerón Estudiantil",
    "organization": "ANDIEP",
    "mission": "Promover la cultura neoespartana en los niños y jóvenes.",
    "attendees": "Primaria: Antonella Marínez - Media General: Susana Peña",
    "manager": "Juan Carlos Marín",
    "date": "11/11/2021",
    "observations": "Culminado",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 37,
    "status": "completed"
  },
  {
    "project": "III Encuentro Online de niños, niñas y jóvenes lectores. ",
    "organization": "ANDIEP",
    "mission": "Fortalecer la lectura y escritura a través de la creación e interpretación de textos narrativos.",
    "attendees": "Todos los niveles: 2 estudiantes de Preescolar, 18 esudiantes de Primaria, 2 estudiantes de MG",
    "manager": "Ana María Núñez",
    "date": "21/09/2021",
    "observations": "Resultado: PENDIENTE",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 37,
    "status": "pending"
  },
  {
    "project": "Olimpiadas Recreativas del Lenguaje",
    "organization": "Sistema de Olimpiadas Recreativas",
    "mission": "Conocer las habilidades y destrezas comunicativas de los estudiantes, con base en el currículo básico nacional, mediante la realización de pruebas periódicas en las que se evalúan de forma recreativa las competencias lingüísticas.",
    "attendees": "Estudiantes de Primaria clasificados en la Olimpiada Preliminar.",
    "manager": "Docentes de Aula. Docentes del área de Lengua y Literatura.",
    "date": "05/10/2021",
    "observations": "Oro: Martina Arroyave 3ero. B, César Vivas, Diego Rdríguez 5to. A, José A Fernándes 5to. A, José R. Ramos 5to. B",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 11,
    "status": "completed"
  },
  {
    "project": "30° Olimpiadas Recreativas de Matemática",
    "organization": "Sistema de Olimpiadas Recreativas",
    "mission": "Desarrollar estrategias para la enseñanza de la Matemática, mejorar el nivel académico y estimular en los niños el uso de sus capacidades intelectuales: comprensión, capacidad de síntesis y juicio crítico.",
    "attendees": "Estudiantes de Primaria clasificados en la Olimpiada Regional",
    "manager": "Docentes de Aula. Docentes del área de Matemática. ",
    "date": "27/03/2022",
    "observations": "Resultado: PENDIENTE",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 25,
    "status": "pending"
  },
  {
    "project": "Olimpiadas Juveniles de Matemática",
    "organization": "Asociación Venezolana de Competencias Matemáticas",
    "mission": "Desarrollar estrategias para la enseñanza de la Matemática, mejorar el nivel académico y estimular en los jóvenes el uso de sus capacidades intelectuales: comprensión, capacidad de síntesis y juicio crítico.",
    "attendees": "Estudiantes de Media General  clasificados en la Olimpiada Regional.",
    "manager": "Docentes de Matemática del Nivel de Educación Media General",
    "date": "24/07/2022",
    "observations": "Resultado: PENDIENTE",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 39,
    "status": "completed"
  },
  {
    "project": "XVI Spelling Bee",
    "organization": "",
    "mission": "Fortalecer el inglés a través del deletreo",
    "attendees": "Todos los niveles, un estudiante por salón desde 3er. grupo",
    "manager": "Dcentes de Inglés: Dalia Hermoso, Lismar Serafini, David Almecija",
    "date": "19/02/2022",
    "observations": "Ganadores: Anabella Piccardo 3er. grupo, Zahir Jalil 2do. grado A, Kimberly Cen 3er. año, Alessandra Doti 5to. año",
    "type": "PROGRAMAS Y PROYECTOS",
    "participants": 27,
    "status": "pending"
  },
  {
    "subject": "Reto de Ciencias Naturales",
    "project": "Cocinando Ciencia: Plastilina Casera",
    "mission": "Elaborar con materiales de uso cotidiano una pastilina casera con la cual se puede propiciar el desarrolo de la motricidad y laceatividad en los niños. ",
    "attendees": "Estudiantes de 2do. año A: Catalina Lenain, Eduardo Peña, Oslybeth Eljuri, Isabella Bello",
    "manager": "José Velásquez (Formación Permanente). Yraida Marcano (Cs. Naturales)",
    "date": "05/05/2022",
    "observations": "Clasificados a la fase Estadal.",
    "type": "RETOS MG",
    "participants": 18,
    "status": "pending"
  },
  {
    "subject": "Reto de Matemática",
    "project": "El juego como aporte en el aprendizaje de las fracciones",
    "mission": "Desarrollar experiencias lúdicas para la enseñanza de las operaciones en números racionales. ",
    "attendees": "Estudiantes de 2do. año: Susana Peña, Giuliana González, Oslybet Eljuri, Catalina Lenaín, Isabella Bello, Santiago Pérez, Fabiana Quijada, Diego Sarmiento. ",
    "manager": "José Velásquez (Formación Permanente). Luis Vásquez y Jesús Salgado (Matemática)",
    "date": "16/03/2022",
    "observations": "Quedamos hasta la fase circuital",
    "type": "RETOS MG",
    "participants": 44,
    "status": "completed"
  },
  {
    "subject": "Reto por Amor y Lealtad a la Patria (GHC y  Soberanía)",
    "project": "Amor y Lealtad a la Patria",
    "mission": "",
    "attendees": "",
    "manager": "José Velásquez (Formación Permanente). Yulimar González (GHC)",
    "date": "13/12/2021",
    "observations": "Quedamos hasta la fase circuital",
    "type": "RETOS MG",
    "participants": 7,
    "status": "completed"
  },
  {
    "subject": "I Olimpiadas Escolares de Historia Neoespartana",
    "project": "Historia Neoespartana",
    "mission": "Promover el conocimiento de la Historia y la Geografía Regional Neoespartana, como una manera de fortalecerlaCultura e Identidad Insular",
    "attendees": "Estudiantes de 6to. grado (6) y estudiantes de MG (5)",
    "manager": "José Velásquez (Formación Permanente)",
    "type": "RETOS MG",
    "participants": 36,
    "date": "01/10/2022",
    "status": "canceled"
  }
]